src/skmultiflow/drift_detection/ddm.py, src/skmultiflow/drift_detection/eddm.py, src/skmultiflow/drift_detection/page_hinkley.py
Hey, I just noted some wrong references to ADWIN in the examples given in the documentation of the drift detection algorithms.
- Remove wrong reference to ADWIN and refer to the correct algorithm.
@scikit-multiflow/scikit-multiflow-repo-admins
=> Documentation: Corrected wrong reference to ADWIN

src/skmultiflow/meta/adaptive_random_forests.py, tests/meta/test_adaptive_random_forests.py, tests/trees/test_hoeffding_adaptive_tree.py
Fixes #62, #63, #65.
- Implementation of `predict_proba` for Adaptive Random Forest (#62).
- Fix a bug where weights were incorrectly passed (#63).
- Above bugfix solves #65 (technically only tested j=2,5,10 and rest still running).
In the discussion of #63 it was mentioned that the fix reduces performance.
However this was based on just the single unit test.
Using the same unit test, but changing the test set (by increasing the initial value of cnt), we see the following values:
| cnt  | master  | PR  |
|---|---|---|
|  0 | 0.6531  | 0.4694  |
|  1 | 0.5306 | 0.4694  |
|  2 | 0.4082  | 0.4694  |
|  3 | 0.5310  | 0.5306  |
|  4 | 0.3877  | 0.5510  |
|  5 | 0.5306  | 5714  |
|  6 | 0.5306  | 0.5918  |
|  7 | 0.4287  | 0.4898  |
|  8 | 0.408  | 0.5510 …
=> Arf predict proba

src/skmultiflow/metrics/measure_collection.py, src/skmultiflow/utils/data_structures.py, tests/metrics/test_measure_collection.py
Fixes #10 .
- add parameter `weitht=1.0` in all methods `add_result` in `measure_collection.py`
- add a call method `check_weights(weight)`
- add documentation
@scikit-multiflow/scikit-multiflow-repo-admins
Checklist
=> Add result weight=1.0 in all methods add_result

docs/installation.rst, docs/user-guide.quick-start-docker.rst, docs/user-guide.rst
- Add documentation for scikit-multiflow Docker 
- Some examples of how to use scikit-multiflow container.
After linking scikit-multiflow Docker Hub repository to Github, the main page of Docker Hub repository will be the same as the Github repository.
=> Add documentation for scikit-multiflow Docker 

src/skmultiflow/lazy/knn.py, src/skmultiflow/lazy/knn_adwin.py
- sys.maxsize seems to be inappropriate
- use windowsize as in https://github.com/scikit-multiflow/scikit-multiflow/blob/19a08d268d744433a52b4812a655035e402c46f2/src/skmultiflow/lazy/knn.py#L95
- e. g. sys.maxsize ends up in a window size of 9223372036854775807 on my system and also in the documentation https://scikit-multiflow.github.io/scikit-multiflow/skmultiflow.lazy.knn_adwin.html?highlight=knn%20adwin#module-skmultiflow.lazy.knn_adwin
* 
* 
* Fixes # . [Optional]
---
Checklist
=> Change default window size in KNN + ADWIN classifier

src/skmultiflow/evaluation/evaluate_prequential.py
Hi, I realized there are two duplicated calls to `evaluate` in two parts of the documentation of the Prequential Evaluator. This PR simply removes them.
*  Removed duplicated lines in the Prequential evaluator
---
I think the checklist doesn't apply to this pull request, since there is no new code proposed.
=> Duplicated lines in prequential documentation example

docs/changelog/v0.4.rst, src/skmultiflow/_version.py, src/skmultiflow/evaluation/evaluate_holdout.py, src/skmultiflow/evaluation/evaluate_prequential.py, src/skmultiflow/metrics/measure_collection.py, src/skmultiflow/utils/data_structures.py, tests/evaluation/test_evaluate_holdout.py, tests/evaluation/test_evaluate_prequential.py, tests/metrics/test_measure_collection.py
During work to improve test coverage of the evaluators a bug was found in the calculation of precision and recall which in places affects the f1-score and geometric mean scores.
The bug is triggered by the order of the observed classes. This is because of the confusion matrix used internally which maps the observed classes by the order of arrival and not the class-value itself.
PR is composed of:
1) Fix bug in precision, recall, f1-score, and geometric mean
2) Improved tests for metrics
3) Improved test coverage for evaluators
---
Checklist
=> Fix bug in precision, recall, F1 and geometric mean scores

src/skmultiflow/trees/intra_cluster_variance_reduction_split_criterion.py
Fixing bug in `IntraClusterVarianceReduction` (`skmultiflow.trees`) calculation.
The current implementation of this split criterion was using `np.sum` to aggregate the `VarianceReduction` values of each target. This PR changes it to `np.mean`, as originally proposed.
* Renaming some variables for conciseness 
* Fixing the way in which `IntraClusterVarianceReduction` is calculated.
---
Checklist
=> Fix in IntraClusterVarianceReduction bug

src/skmultiflow/trees/nodes/split_node.py, tests/trees/test_hoeffding_tree.py
This PR fixes a bug in the depth calculation for Hoeffding Trees.
* Fix the depth calculation for Hoeffding Trees: when iterating over their nodes, the HTs were accessing the key values of their internal structures rather than the actual nodes.
* The bug and proposed fix have no impact on the performance of the Hoeffding Tree. This method is mainly used for informative purposes via the `get_model_measurements` method.
---
Checklist
=> [BUG] Fix in subtree_depth calculation

src/skmultiflow/trees/hoeffding_adaptive_tree.py, src/skmultiflow/trees/nodes/ada_learning_node.py, tests/trees/test_hoeffding_adaptive_tree.py
Performing bootstrap sampling in the leaf nodes improves (in most cases) the performance of the Hoeffding Adaptive Tree Classifier. This was enabled in version 0.4.0:
https://github.com/scikit-multiflow/scikit-multiflow/blob/cda70f059ca4cf1b6c9b7fe9bbcc70dcc5e480d4/src/skmultiflow/trees/hoeffding_adaptive_tree.py#L313-L315
This strategy is an improvement over the original method, consequently, it should be **optional** in our implementation in order for the user to decide whether to use it or not.
This PR updates the signature of the Hoeffding Adaptive Tree Classifier to include a new `bootstrap_sampling` option:
```python
def __init__(self,
max_byte_size=33554432,
memory_estimate_period=1000000,
grace_period=200,
split_criterion='info_gain', …
```
=> [FEATURE] Bootstrap sampling option for the Hoeffding Adaptive Tree Classifier

src/skmultiflow/trees/nodes/node.py
* Remove Syntax Warning in trees/nodes/node.py by changing 'foo is not 0' into 'foo != 0'
---
Checklist
=> Remove syntax warning in trees/nodes/node.py .

src/skmultiflow/drift_detection/adwin.py
* Fix a bug in the computation of the `incremental_variance` in `__compress_buckets()`, where a square was missing:
```python
incremental_variance = n1 * n2 * (u1 - u2) / (n1 + n2)
```
```python
incremental_variance = n1 * n2 * ((u1 - u2) * (u1 - u2)) / (n1 + n2)
```
* Fix does not seem to have a significant impact on methods relying on ADWIN to detect drift. 
---
Checklist
=> Bugfix in ADWIN.

src/skmultiflow/bayes/utils.py
* Add additional check if the sum of class distribution values is zero 
* Prevents division by zero in https://github.com/scikit-multiflow/scikit-multiflow/blob/8c69795850beb277cbd094c38e53c8ceb3cd2ae9/src/skmultiflow/bayes/utils.py#L31
* Addresses #165  . 
The bug occurred when using ARF with leaf_predicition='nba' (default setting) and the sum of class distribution values being equal to zero.
---
Checklist
=> [BUG] Add check for zero sum to avoid division by zero in Naive Bayes Prediction

src/skmultiflow/meta/online_rus_boost.py, src/skmultiflow/rules/very_fast_decision_rules.py
Refers to this issue:
**Inconsistent use of sample_weight vs weight parameters [BUG] #190**
This should be very minor: partial_fit and fit functions, if they have sample weights, this parameter should have a consistent name. I found (only) two instances where the parameter is called **weight** instead of **sample_weight** (for some reason, I thought there were more). I changed these to sample_weight (+documentation) and checked that it doesn't break anything. 
I am very impressed by this library, and all the work all of you have been putting in. Perhaps to flag: I didn't find any tests using the weights.
=> minor: rn parameter name from weight to sample_weight

src/skmultiflow/lazy/knn_classifier.py, src/skmultiflow/meta/classifier_chains.py, src/skmultiflow/meta/online_adac2.py, src/skmultiflow/meta/online_boosting.py, src/skmultiflow/meta/online_csb2.py, src/skmultiflow/meta/online_rus_boost.py, src/skmultiflow/meta/online_smote_bagging.py, src/skmultiflow/meta/online_under_over_bagging.py, src/skmultiflow/rules/very_fast_decision_rules.py
Stream estimators shall be able to return predictions at any time. Some methods were failing when predictions were requested and the model was empty. This PR addresses this issue for:
* `KNNClassifier`
* `OnlineAdaC2Classifier`
* `OnlineBoosting`
* `OnlineUnderOverBaggingClassifier`
* `OnlineSMOTEBaggingClassifier`
* `OnlineCSB2Classifier`
- Return a default value (zero) for predictions if the model is empty.
- Update documentation of the KNNClassifier.
- Handle RuntimeWarning from numpy operations in `Online****`
- Fix typo in example code for `MonteCarloClassifierChain`
- Fixes #158
---
Checklist
=> Fix bug in methods that failed when `predict` was called before the first partial_fit/fit

src/skmultiflow/evaluation/base_evaluator.py, src/skmultiflow/evaluation/evaluate_holdout.py, src/skmultiflow/evaluation/evaluate_prequential.py
- Fix bug in evaluators when model_size or running_time are listed first in the metrics option
- Update evaluators documentation to clarify that model_size and running_time are not plotted but their values can be retrieved via the output_file.
- Fixes #186 
---
Checklist
=> Fix bug in evaluators when model_size or running_time are listed first in the metrics option

src/skmultiflow/metrics/_classification_performance_evaluator.pyx
This PR corrects typos in `ClassificationPerformanceEvaluator`'s documentation and also ensures the PEP257 style for docstrings.
=> Correct typos in classification performance evaluator doc and ensure PEP257's docstring style.

src/skmultiflow/meta/accuracy_weighted_ensemble.py, src/skmultiflow/metrics/measure_collection.py, src/skmultiflow/prototype/robust_soft_learning_vector_quantization.py, src/skmultiflow/trees/isoup_tree.py, src/skmultiflow/trees/stacked_single_target_hoeffding_tree_regressor.py
This PR changes power operations to increase performance.
- `a * a` is about three times faster than `a ** 2`, so prefer it whenever it does not hinder readability.
- a instance of `a ** 0.5` in `RobustSoftLearningVectorQuantization` is also changed to `np.sqrt(a)`, for clarity
---
Checklist
=> Optimise a ** 2 in a * a.

src/skmultiflow/trees/split_criterion/info_gain_split_criterion.py
* Add a check in `skmultiflow.trees.split_criterion.InfoGainSplitCriterion` to avoid potential division by zero.
---
Checklist
=> Add check in InfoGainSplitCriterion to avoid division by zero

src/skmultiflow/trees/arf_hoeffding_tree.py, src/skmultiflow/trees/extremely_fast_decision_tree.py, src/skmultiflow/trees/hoeffding_adaptive_tree.py, src/skmultiflow/trees/hoeffding_adaptive_tree_regressor.py, src/skmultiflow/trees/hoeffding_tree.py, src/skmultiflow/trees/hoeffding_tree_regressor.py, src/skmultiflow/trees/isoup_tree.py, src/skmultiflow/trees/label_combination_hoeffding_tree.py, src/skmultiflow/trees/nodes/ada_learning_node.py, src/skmultiflow/trees/nodes/ada_learning_node_for_regression.py, src/skmultiflow/trees/nodes/ada_split_node.py, src/skmultiflow/trees/nodes/ada_split_node_for_regression.py, src/skmultiflow/trees/nodes/lc_active_learning_node.py, src/skmultiflow/trees/stacked_single_target_hoeffding_tree_regressor.py, tests/trees/test_hoeffding_adaptive_tree.py, tests/trees/test_regression_hoeffding_adaptive_tree.py
This PR fixes #154.
Besides, it corrects some typos in the adaptive split nodes where node identifiers were accessed, rather than their content. Incorrect variable naming is also fixed.
Finally, I changed the way Hoeffding Adaptive Tree Regressor monitors its errors using ADWIN. Previously, the errors were calculated using normalized target values and predictions (using the z-score approach, as usually done by the tree regressors). However, as stated in [ADWIN's paper](https://epubs.siam.org/doi/abs/10.1137/1.9781611972771.42), a bounded error metric (w.r.t. its range) is expected. For that reason, I implemented a mechanism to incrementally normalize the monitored error metrics in the `[0,1]` range.
Thanks, @jacobmontiel, for the suggestion.
* Fix …
=> [BUG/ENHANCEMENT] Coverage tests for HAT/HATR and bug fixes

src/skmultiflow/anomaly_detection/half_space_trees.py, tests/anomaly_detection/test_half_space_trees.py
The current implementation of the `HalfSpaceTrees` includes the number of features (`n_features`) as a required parameter. This goes against the strategy followed in other implementations where such information is obtained from the data itself.
- Remove `n_features` as required parameter for initializing a `HalfSpaceTrees` instance. `n_features` is now obtained from the data as it is passed for training.
- Enforce PEP8 char line limit
- Minor cosmetic changes
---
=> Minor updates for HalfSpaceTrees

src/skmultiflow/trees/hoeffding_adaptive_tree_regressor.py, src/skmultiflow/trees/isoup_tree.py, src/skmultiflow/trees/nodes/ada_learning_node.py, src/skmultiflow/trees/nodes/ada_learning_node_for_regression.py, src/skmultiflow/trees/nodes/ada_split_node.py, src/skmultiflow/trees/nodes/ada_split_node_for_regression.py, src/skmultiflow/trees/nodes/lc_active_learning_node.py, tests/trees/test_hoeffding_adaptive_tree.py, tests/trees/test_hoeffding_adaptive_tree_regressor.py
While syncing my fork with the upstream during the development of #223, I accidentally ended up overwriting (effectively rolling back) some changes implemented in #220. This PR makes sure that those operations are applied.
* Reapply missing operations from #220
---
=> [BUG] Reapply lost fixes from #220

src/skmultiflow/evaluation/evaluate_holdout.py, src/skmultiflow/evaluation/evaluate_prequential.py
This PR updates the default behavior of `EvaluatePrequential` when reporting the last measurements and writing the output file. The current implementation updates metrics until the last multiple of `n_wait` which might be less than the user-defined `max_samples`, provided that there are enough samples in the stream. For example, if `max_samples=2500`and `n_wait=200` then the last metrics update is performed at `sample_count=2400` 
Evaluators (prequential and hold out) **must** include measurements for up to `max_samples` regardless if `n_wait` has been reached at the end of the evaluation. In the example above, a final metrics update must be performed for the remaining `100` samples in the stream, to get the final metrics at `sample_count=2500`.
---
=> Make EvaluatePrequential and EvaluateHoldout report all processed samples in the output file

src/skmultiflow/bayes/naive_bayes.py, src/skmultiflow/meta/leverage_bagging.py, tests/meta/test_leverage_bagging.py
- Correct the value passed to ADWIN in `LeveragingBaggingClassifier` to monitor performance, previously this value was inverted.
- Add protection against division by zero.
- Update test cases and improve coverage.
- Remove dead code in `LeveragingBaggingClassifier`.
- Replace `adwin_ensemble` creation with list comprehension.
- Remove obsolete `try` in `LeveragingBaggingClassifier ` from the time when not all models were defaulting to prediction=[0] when empty. This is no longer necessary as now all classifiers return a valid value.
- Make the output of `predict_proba` in `NaiveBayes` 2D when the model is empty.
- Fixes #240 
---
=> Fix bug in the LeveragingBaggingClassifier and NaiveBayes

src/skmultiflow/meta/online_smote_bagging.py, src/skmultiflow/trees/hoeffding_adaptive_tree_regressor.py, src/skmultiflow/trees/hoeffding_tree_regressor.py
* Let numpy infer the infix notation instead of using np.ufunc().
---
---
This is a fresh & up-to-date version of #181
=> Use Numpy infix notation.

tests/meta/test_batch_incremental.py, tests/meta/test_classifier_chains.py, tests/meta/test_learn_nse.py, tests/meta/test_learn_pp.py, tests/meta/test_multi_output_learner.py, tests/meta/test_regressor_chains.py
With the recent release of `sklearn==0.23` some of the tests in our CI/CD pipeline have broken. This problem happened because of the following change in sklearn, which is stated in the new version's changelog:
In simple terms, the string representation of a sklearn model only exhibits the parameters that were changed by the user, i.e., the ones that did not keep the suggested default values. 
Some of our automatic tests depend on sklearn and compare the skmultiflow models' descriptions with template strings. These strings previously depicted all the existing parameters of the sklearn models (which were usually used as base models for skmultiflow's meta models). This is no longer the case, as previously described.
We had two options:
1. Force sklearn to keep showing all the parameters and …
=> Fix CI/CD pipeline and streamline sklearn-dependent tests

src/skmultiflow/core/base.py, src/skmultiflow/data/data_stream.py, tests/data/test_data_stream.py
Addresses two minor problems that are making fail the recently added linting check:
* Remove inadvisable usage of 'l' as variable name (E741) in `core.base`
* Fix missing string.format parameter (F523) in `data.DataStream`
---
=> Fix PEP8 problems

src/skmultiflow/meta/batch_incremental.py
*  Fixes an error in `BatchIncrementalClassifier` when the first call to `partial_fit` contains fewer samples than `window_size`.
---
=> Fix bug in BatchIncrementalClassifier

src/skmultiflow/data/concept_drift_stream.py, tests/data/test_concept_drift_stream.py
Use `None` as the default value instead of `0.0`. Because the old default value is confusing with the range of alpha which is `(0.0, 90.0]`.
=> Update default value for alpha in ConceptDriftStream
